// A starter catalogue of professional fields and skills (FR-CHR-14) for a marketing and media
// group, so the first people to fill in their profile pick from a list instead of facing an empty
// box. Seeded by `pnpm db:seed`, only the names the catalogue does not have yet; HR corrects,
// merges and removes entries afterwards on People → Professional fields & skills. Plain data: no
// I/O. Every name is written the way the app stores one — each word capitalised (a test checks).
import { toSearchKey } from "../../lib/text";

export const COMPETENCY_SEED: { profession: readonly string[]; skill: readonly string[] } = {
  // What a person does for a living: the fields the group's teams work in, then the back office.
  profession: [
    "Social Media",
    "Community Management",
    "Content Marketing",
    "Copywriting",
    "Scriptwriting",
    "Graphic Design",
    "Brand Identity",
    "UI/UX Design",
    "Motion Graphics",
    "Video Production",
    "Video Editing",
    "Cinematography",
    "Directing",
    "Photography",
    "Media Buying",
    "Performance Marketing",
    "SEO",
    "Email Marketing",
    "Influencer Marketing",
    "Public Relations",
    "Event Management",
    "Brand Strategy",
    "Marketing Strategy",
    "Market Research",
    "Data Analytics",
    "Account Management",
    "Business Development",
    "Sales",
    "Customer Service",
    "Project Management",
    "Human Resources",
    "Recruitment",
    "Compensation & Benefits",
    "Accounting",
    "Finance",
    "Legal",
    "Administration",
    "IT Support",
    "Web Development",
  ],
  // What a person is able to do, whatever their field: abilities first, then languages and tools.
  skill: [
    "Problem Solving",
    "Critical Thinking",
    "Communication",
    "Presentation",
    "Public Speaking",
    "Negotiation",
    "Teamwork",
    "Leadership",
    "Coaching",
    "Decision Making",
    "Conflict Resolution",
    "Time Management",
    "Planning",
    "Creativity",
    "Storytelling",
    "Attention To Detail",
    "Adaptability",
    "Client Relations",
    "Research",
    "Data Analysis",
    "Reporting",
    "Budgeting",
    "Writing",
    "Editing",
    "English",
    "Japanese",
    "Korean",
    "Chinese",
    "Microsoft Excel",
    "Google Workspace",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe Premiere Pro",
    "Adobe After Effects",
    "Figma",
    "Canva",
    "CapCut",
    "Meta Ads",
    "Google Ads",
    "TikTok Ads",
    "Google Analytics",
  ],
};

/** The seed as rows of `competency`. */
export function competencySeedRows(): { kind: "profession" | "skill"; name: string; searchName: string }[] {
  return (["profession", "skill"] as const).flatMap((kind) => COMPETENCY_SEED[kind].map((name) => ({ kind, name, searchName: toSearchKey(name) })));
}
