import {
  Asterisk,
  Award,
  Banknote,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  CalendarDays,
  CalendarRange,
  CheckCheck,
  ChartNoAxesColumn,
  CircleUser,
  FileText,
  Fingerprint,
  GitBranch,
  House,
  KeyRound,
  ListChecks,
  ListTodo,
  Megaphone,
  Network,
  Package,
  Receipt,
  Scale,
  ScrollText,
  ShieldCheck,
  Sparkles,
  SquareKanban,
  Target,
  Timer,
  ToggleRight,
  UserPlus,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * One icon per navigation entry, in the reference's 16px outline weight. A key without an icon
 * falls back to the asterisk of the workspace mark rather than leaving the row ragged.
 */
const ICONS: Record<string, LucideIcon> = {
  home: House,
  announcements: Megaphone,
  kudos: Award,
  checkIn: Fingerprint,
  me: CircleUser,
  people: Users,
  reports: ChartNoAxesColumn,
  attendance: CalendarDays,
  leave: CalendarRange,
  requests: Receipt,
  work: SquareKanban,
  assets: Package,
  bookings: CalendarRange,
  ops: ShieldCheck,
  performance: Target,
  recruit: Briefcase,
  interviews: Timer,
  referrals: UserPlus,
  kb: BookOpen,
  assistant: Sparkles,
  payslips: Wallet,
  payroll: Banknote,
  tasks: ListTodo,
  approvals: CheckCheck,
  notifications: Bell,
  entities: Building2,
  org: Network,
  flags: ToggleRight,
  checklists: ListChecks,
  documentTemplates: FileText,
  approvalFlows: GitBranch,
  requestTypes: Receipt,
  roles: KeyRound,
  rules: Scale,
  audit: ScrollText,
  jobs: Timer,
};

/** The icon of a navigation entry, ready to render: 16px, muted, decorative. */
export function NavIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Asterisk;
  return <Icon className={className} aria-hidden />;
}
