// Generated by `pnpm i18n:routes` (scripts/i18n-route-namespaces.ts) — do not edit by hand.
// The message namespaces the browser is handed: the app's shell, and what each section adds.

export const SHELL_NAMESPACES: readonly string[] = ["controls", "errors", "feedback", "files", "forms.fieldErrors", "impersonation", "notifications.push", "richText", "theme", "welcome", "work.palette"];

export const SEGMENT_NAMESPACES = {
  admin: ["approvals.flows", "approvals.types", "brands", "documents.designer", "documents.errors", "documents.kind", "documents.tier", "entities", "flags", "imports", "jobs.runNow", "org", "rbac", "requests.designer", "requests.errors", "roles", "rules"],
  announcements: ["comms"],
  approvals: ["approvals", "attendance.months", "attendance.position", "attendance.requests", "changeRequests", "leave", "records.errors", "requests"],
  assets: ["assets.assign", "assets.bookings", "assets.categories", "assets.digital", "assets.enums", "assets.errors", "assets.form", "assets.handover", "assets.licences", "assets.return", "assets.seats", "assets.status", "imports"],
  assistant: ["assistant"],
  attendance: ["attendance.checkIn", "attendance.devices", "attendance.kiosk", "attendance.months", "attendance.policy", "attendance.position", "attendance.requests", "attendance.review", "attendance.settings", "imports", "records.errors"],
  checklists: ["checklists", "work.errors"],
  crm: ["approvals", "crm", "projects", "work"],
  daily: ["assistant.drafts", "daily"],
  documents: [],
  feedback: [],
  home: ["comms"],
  kb: ["kb", "roles"],
  kudos: ["comms"],
  leave: ["imports", "leave", "records.errors"],
  me: ["approvals", "attendance.myFace", "changeRequests", "lifecycle", "people", "records", "tasks"],
  notifications: ["notifications"],
  ops: ["ops", "roles"],
  payroll: ["approvals", "imports", "payroll.bonus", "payroll.components", "payroll.errors", "payroll.imports", "payroll.offers", "payroll.parallel", "payroll.payments", "payroll.payslips", "payroll.policy", "payroll.profiles", "payroll.reports", "payroll.retro", "payroll.rules", "payroll.runs", "payroll.salaries", "payroll.statutory", "rules.void"],
  payslips: ["payroll.payments", "payroll.payslips"],
  people: ["approvals", "documents", "imports", "lifecycle", "people", "records", "tasks"],
  performance: ["imports", "performance"],
  projects: ["approvals", "assistant.drafts", "projects", "work"],
  recruit: ["people", "recruit"],
  reports: ["reports.schedules"],
  requests: ["approvals", "requests"],
  "step-up": ["stepUp"],
  tasks: [],
  today: ["crm", "daily", "tasks", "work"],
  work: ["assets.digital.platform", "assistant.drafts", "checklists.library", "checklists.stages", "daily", "imports", "projects", "work"],
} as const satisfies Record<string, readonly string[]>;

export type AppSegment = keyof typeof SEGMENT_NAMESPACES;
