// Generates which agent tools each role is offered (Phase 13 R2) from the tool registry and the role
// catalogue, and compares it with the committed copy in docs/. A tool the asker's roles could never
// use is not offered to the model at all (SRS §4.13b rule 1), so this table is what a model can
// even ask for, per role — any change to a tool's offer or to a role shows up as a reviewable diff.
// Regenerate with: pnpm vitest run tests/agent-tool-matrix.test.ts -u
import { expect, test } from "vitest";
import { type AskerFacts, NO_FACTS } from "@/modules/ai/agent/registry";
import { AGENT_TOOLS } from "@/modules/ai/agent/tools";
import type { Principal } from "@/modules/platform/rbac/policy";
import { ROLES } from "@/modules/platform/rbac/roles";

const principalOf = (roles: readonly (typeof ROLES)[number][]): Principal => ({ personId: "p", workforceType: "employee", grants: roles.map((role) => ({ role, scope: { type: "group" } })) });

test("the agent's tool matrix matches docs/agent-tool-matrix.md", async () => {
  const rows: { label: string; principal: Principal; facts: AskerFacts }[] = [
    { label: "employee, no role", principal: principalOf([]), facts: NO_FACTS },
    { label: "employee who leads a team or project", principal: principalOf([]), facts: { ...NO_FACTS, leadsWork: true } },
    { label: "employee with people reporting to them", principal: principalOf([]), facts: { ...NO_FACTS, managesPeople: true } },
    { label: "employee who owns a deal or manages a client account", principal: principalOf([]), facts: { ...NO_FACTS, worksAccounts: true } },
    { label: "collaborator", principal: { personId: "p", workforceType: "collaborator", grants: [] }, facts: NO_FACTS },
    ...ROLES.map((role) => ({ label: `\`${role}\``, principal: principalOf([role]), facts: NO_FACTS })),
  ];
  const tools = AGENT_TOOLS;
  const lines = [
    "# Agent tool matrix",
    "",
    "Generated by `tests/agent-tool-matrix.test.ts` from `src/modules/ai/agent/tools/` and `src/modules/platform/rbac/roles.ts`. Do not edit by hand; run `pnpm vitest run tests/agent-tool-matrix.test.ts -u` after changing a tool or a role and review the diff.",
    "",
    "A tool that is not offered is not in the request: the model cannot ask for it. A tool that is offered still reads as the asker — through its module's own door, which may answer with less or with nothing (SRS §4.13b rules 1–3). Roles are shown granted over the whole group; a narrower scope offers the same tools and the modules narrow what they return.",
    "",
    "## The tools",
    "",
    "| Tool | Kind | Module | Highest tier it reads | Step-up | Tags |",
    "|---|---|---|---|---|---|",
    ...tools.map((tool) => `| \`${tool.name}\` | ${tool.kind} | ${tool.module} | ${tool.tier} | ${typeof tool.stepUp === "function" ? "for pay" : tool.stepUp ? "yes" : "·"} | ${tool.tags.join(", ") || "·"} |`),
    "",
    "## Offered to",
    "",
    `| Asker | ${tools.map((tool) => `\`${tool.name}\``).join(" | ")} |`,
    `|---|${tools.map(() => "---").join("|")}|`,
    ...rows.map((row) => `| ${row.label} | ${tools.map((tool) => (tool.offeredTo(row.principal, row.facts) ? "✓" : "·")).join(" | ")} |`),
    "",
  ];
  await expect(lines.join("\n")).toMatchFileSnapshot("../docs/agent-tool-matrix.md");
});
