// Generates the role × permission × tier matrix from the role catalogue and compares it with the
// committed copy in docs/. Any change to a role therefore shows up as a reviewable diff
// (NFR-SEC-02). Regenerate with: pnpm vitest run tests/permission-matrix.test.ts -u
import { expect, test } from "vitest";
import { can, canReadTier, type Principal } from "@/modules/platform/rbac/policy";
import { ROLE_DEFINITIONS, ROLES, TIERS, type Permission } from "@/modules/platform/rbac/roles";

const PERMISSIONS = [
  "org:read",
  "org:manage",
  "rbac:manage",
  "audit:read",
  "person:read",
  "person:manage",
  "attendance:manage",
  "leave:manage",
  "payroll:read",
  "payroll:propose",
  "payroll:approve",
  "payroll:pay",
  "rules:propose",
  "payroll:rules",
  "recruit:manage",
  "asset:manage",
  "report:read",
] as const satisfies readonly Exclude<Permission, "*">[];

const ENTITY = "entity-a";
const inScope = { entityId: ENTITY, departmentId: "dept-a", teamId: "team-a", personId: "someone", managerId: "their-manager" };
const outOfScope = { ...inScope, entityId: "entity-b" };

const table = (head: string[], rows: string[][]) => [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`, ...rows.map((row) => `| ${row.join(" | ")} |`)].join("\n");
const mark = (yes: boolean) => (yes ? "✓" : "·");

function highestTier(principal: Principal, target: typeof inScope): string {
  return [...TIERS].reverse().find((tier) => canReadTier(principal, target, tier)) ?? "none";
}

test("the permission matrix matches docs/permission-matrix.md", async () => {
  const granted = (role: (typeof ROLES)[number]): Principal => ({ personId: "viewer", workforceType: "employee", grants: [{ role, scope: { type: "entity", id: ENTITY } }] });

  const permissions = table(
    ["Role", ...PERMISSIONS.map((permission) => `\`${permission}\``)],
    ROLES.map((role) => [`\`${role}\``, ...PERMISSIONS.map((permission) => mark(can(granted(role), permission, inScope)))]),
  );

  const tiers = table(
    ["Viewer", "Highest tier readable", "Outside the grant's scope"],
    [
      ...ROLES.map((role) => [`\`${role}\``, highestTier(granted(role), inScope), highestTier(granted(role), outOfScope)]),
      ["the person themselves", highestTier({ personId: "someone", workforceType: "employee", grants: [] }, inScope), "—"],
      ["their line manager", highestTier({ personId: "their-manager", workforceType: "employee", grants: [] }, inScope), "—"],
      ["any other employee", highestTier({ personId: "viewer", workforceType: "employee", grants: [] }, inScope), "—"],
      ["a collaborator", highestTier({ personId: "viewer", workforceType: "collaborator", grants: [] }, inScope), "—"],
    ],
  );

  // Every permission in the catalogue must appear as a column, or the matrix silently goes stale.
  const used = new Set(ROLES.flatMap((role) => ROLE_DEFINITIONS[role].permissions.filter((permission) => permission !== "*")));
  expect([...used].filter((permission) => !(PERMISSIONS as readonly string[]).includes(permission))).toEqual([]);

  const document = [
    "# Permission matrix",
    "",
    "Generated by `tests/permission-matrix.test.ts` from `src/modules/platform/rbac/roles.ts`. Do not edit by hand; run `pnpm vitest run tests/permission-matrix.test.ts -u` after changing a role and review the diff.",
    "",
    "## Permissions by role",
    "",
    "A role acts only inside the scope of its grant (group, entity, department or team). Nothing is granted outside it.",
    "",
    permissions,
    "",
    "## Personal data: highest sensitivity tier readable",
    "",
    `Tiers, least to most sensitive: ${TIERS.map((tier) => `\`${tier}\``).join(" < ")}. Each role is granted on one entity; the person viewed belongs to it (middle column) or to another entity (right column).`,
    "",
    tiers,
    "",
  ].join("\n");

  await expect(document).toMatchFileSnapshot("../docs/permission-matrix.md");
});
